name: Update Incidence

on:
  # run every day at 8:00, 10:00, 12:00
  schedule:
    - cron: '0 8,10,12 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  incid-update:
    name: Update incidence
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python deps
      run: pip install -r requirements.txt
    - run: head -n 30 index.html
    - name: Update incidence
      run: python update_rki_incidence.py
    - run: head -n 30 index.html
    - name: Push a commit if any files updated
      run: |
        git status
        git diff
        git config user.name github-actions
        git config user.email github-actions@github.com
        git diff-index --quiet HEAD || git commit -am "update incidence"
        git push